### ISSUE TITLE
Issue with task 1.6* Phase change of the "Basic.Gates" kata

### ISSUE THREAD

**Issue by AlainChance** [Microsoft/QuantumKatas#10]
Hello,
Pertaining to task 1.6* Phase change of the "Basic.Gates" kata:
```
// Task 1.6*. Phase change
    // Inputs: 
    //     1) A qubit in state β|0⟩ + γ|1⟩.
    //     2) Angle alpha, in radians, represented as Double
    // Goal:  Change the state of the qubit as follows:
    //        If the qubit is in state |0⟩, don't change its state.
    //        If the qubit is in state |1⟩, change its state to exp(i*alpha)|1⟩.
    //        If the qubit is in superposition, change its state according to the effect on basis vectors.
```
The reference solution `Rz(alpha, q);` doesn't seem to be correct, since: 
Rz(alpha) |0> = exp(-i * alpha/2) |0> 
Rz(alpha) |1> = exp(i * alpha/2) |1>
Please check.

**Comment by tcNickolas** [comment]
If we apply Rz(alpha) to qubit in state `β|0⟩ + γ|1⟩`, we'll get 
`exp(-i * alpha/2) β|0⟩ + exp(i * alpha/2) γ|1⟩ = exp(-i * alpha/2) (β|0⟩ + exp(i * alpha) γ|1⟩)`, which is the required state up to a global phase `exp(-i * alpha/2)`. Since the global phase can always be ignored, Rz(alpha) performs the required transformation.

Hope that helps!

**Comment by AlainChance** [comment]
Yes, it helps!

I suggest updating the goal of task 1.6* Phase change of the "Basic.Gates" kata as follows: 
```
Goal: Change the state of the qubit according to the following transformation on basis states:
leave |0> unchanged and map |1> to exp(i*alpha)|1⟩.
```
Thanks!
