### ISSUE TITLE
Notebooks on Binder lose connection

### ISSUE THREAD

**Issue by geduardo** [microsoft/QuantumKatas#164]
I was doing the katas online on Binder but each time I leave the notebook inactive for some minutes (maybe 10 (?)) Binder loses the connection and it is impossible to reconnect without restarting the whole Notebook and losing what was written. I tried with Edge and Chrome and in both occurs the same issue. Also with different connections.

This can get frustrating when you're advanced in the notebook and after being thinking about the solution of an exercise you have to make a copy of everything and reset the notebook again because Binder lost the connection. Especially when you have to repeat this process several times per notebook.

I don't know if this is a problem with Binder or can be solved here. If it cannot be solved please close the issue. For now, I'll run the notebooks locally.

**Comment by tcNickolas** [comment]
This is expected behavior for Binder - inactive sessions are terminated after 10 minutes (see [the relevant section of the FAQ](https://mybinder.readthedocs.io/en/latest/faq.html#how-long-will-my-binder-session-last)). We are exploring other hosting options, but they will take time to implement. For now, if you're spending significant amount of time working on the tasks, it makes perfect sense to set up the notebooks to run locally.
