### ISSUE TITLE
Issue with ComplexArithmetic Exercise 1 Solution Code

### ISSUE THREAD

**Issue by natelowry** [microsoft/QuantumKatas#264]
Thanks for these awesome tutorials and katas!

In the ComplexArithmetic workbook answers.
>Exercise 1: Powers of  𝑖 .
>Input: An even integer  𝑛 .
>Goal: Return the  𝑛 th power of  𝑖 , or  𝑖𝑛 .

The solution code [here](https://github.com/microsoft/QuantumKatas/blob/8c9bc84c8d736577d43e4ec7305da95061e4235d/tutorials/ComplexArithmetic/Workbook_ComplexArithmetic.ipynb?short_path=f7c9afe#L94
) is below:
```
@exercise
def imaginary_power(n : int) -> int:
    # If n is divisible by 4
    if n % 4 == 0:
        return 1
    else:
        return -1
```

While that works for the divisible by 4 case, it doesn't really work for the not-divisible by 4 cases.  The answer should only be `-1` if `n % 4 == 2`, right?  There needs to be another check to see if it could also be `-i` or `i` as well.

Am I missing something super simple?

**Comment by tcNickolas** [comment]
I'm glad you're finding this project helpful!

In this task the input promises that n will be even, so either divisible by 4 or give remainder 2 when dividing by 4; thus the result is always an integer. (In the first iteration of this tutorial, we offered the full version of the task, asking to return a complex tuple, but that turned out to be more complicated for the first task of this tutorial than we wanted it to be, so we cut back to a simpler version.)

**Comment by natelowry** [comment]
@tcNickolas I see!  I didn't read the input correctly.  Thanks!
