### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by benvial** [microsoft/QuantumKatas#280]
When running the BasicGates.ipynb notebook I get the error:

No namespace with the name "Microsoft.Quantum.Intrinsic" exists.

Any idea of why?

I am on Linux (CentOS Linux release 7.7.1908)

`
dotnet --version
3.0.100
`
`
python --version
Python 3.7.0
`
`
jupyter --version
4.4.0
`

**Comment by tcNickolas** [comment]
I have a theory that your installed IQ# version doesn't match the version used by the notebook. What do you get when you execute the first cell of the notebook (`%package Microsoft.Quantum.Katas::<some version>`)? The version of `Microsoft.Quantum.Standard` you'll get is the IQ# version you have installed - if it doesn't match the version of `Microsoft.Quantum.Katas` you'll need to install a matching IQ# version (follow the instructions right below that first cell).

At the moment the Katas are not on the latest QDK version because of a performance issue we've observed when trying to upgrade (https://github.com/microsoft/iqsharp/issues/79), so this is a likely root cause.

Let us know if this is the case and installing a matching version of IQ# works!

**Comment by benvial** [comment]
That was indeed the case, the version of Microsoft.Quantum.Katas (0.10.1911.1607) was matching the one displayed in the notebook but the version of Microsoft.Quantum.Standard was different.

Solved by installing the correct version

`dotnet tool install microsoft.quantum.iqsharp -g --version 0.10.1911.1607`

```
Microsoft.Quantum.Standard::0.10.1911.1607
Microsoft.Quantum.Katas::0.10.1911.1607
```

Everything works fine now. Thanks for your help!

Closing
