### ISSUE TITLE
Hello! Using py to run Katas sample? Possible?

### ISSUE THREAD

**Issue by nathanawmk** [microsoft/QuantumKatas#304]
Hello! Using py to run Katas sample? Possible? 

https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall

**Comment by tcNickolas** [comment]
Hi,

You can run the Katas either as [C# projects](https://docs.microsoft.com/quantum/install-guide/csinstall) using Visual Studio, VS Code or any editor you like with command line, or as [Jupyter Notebooks](https://docs.microsoft.com/quantum/install-guide/qjupyter). Some of the Jupyter Notebook tutorials (the ones dealing with classical computations only or the ones that require visualization) are implemented using Python, but most of them use Q#.

If your preferred setup is Python, you'll probably want to use the Jupyter Notebooks version, since the setup is closer to the Python one (and the tasks presentation is more polished).

**Comment by tcNickolas** [comment]
I'll close this issue for now; please let us know if you run into any issues using the Katas with Jupyter Notebooks!
