### ISSUE TITLE
Alternative solution to Measurements/Hardy State

### ISSUE THREAD

**Issue by wsgac** [microsoft/QuantumKatas#314]
Hi,

I was fooling around with an approach slightly different from the one in the reference implementation and was able to come up with the following:
```
operation Hardy_State (qs : Qubit[]) : Unit {
    Ry(2.0*ArcCos(Sqrt(10.0/12.0)), qs[0]);
    (ControlledOnInt(1, H))([qs[0]], qs[1]);
    (ControlledOnInt(0, Ry))([qs[0]], (2.0*ArcCos(Sqrt(9.0/10.0)), qs[1]));
}
```
Feel free to include this as an alternative and to comment if this approach has any downsides.

**Comment by tcNickolas** [comment]
*I'm assuming you mean Superposition/Hardy State task, I don't think we have one about this state in Measurements :-)*

Indeed, you can use H gate here instead of Ry with rotation by PI()/4 freely; those two gates differ only by the second column of their matrix representation (H gate has 1 in the first row and -1 in the second row, and Ry(PI()/4) has -1 in the first row and 1 in the second row), but since you only apply them to |0> state, this difference has no effect. Using Ry is more general approach, since it allows to split the |0> state into any superposition of |0> and |1>, as long as they both have real amplitudes.

It's probably not worth including it as a separate solution (since only 1 gate is different), but might be worthwhile to leave a comment in the solution itself, mentioning that you can use H instead of Ry here. Let me know if you'd like to do that!

(Sorry for the delay replying! I wanted to finish https://github.com/microsoft/QuantumKatas/pull/282 first to reduce the number of threads about Superposition solutions)

**Comment by mbuchberger1967** [comment]
Hi,
I agree that in this special case we could use a Controlled H instead of a Controlled Ry, but the maths I just added to this task are guiding the reader to the Controlled Ry gate. 
This is why I changed the reference impl to use a Controlled Ry, and just left a comment that in this special case one could also use a Controlled h. 
I hope you agree.
BR
Markus

**Comment by tcNickolas** [comment]
https://github.com/microsoft/QuantumKatas/commit/8c59741736d8b5a979f16bc88eacae620849635c added a comment to the solution mentioning that Controlled H is an option in this solution, so I think we can close this issue.
