### ISSUE TITLE
Add math to better understand Grover's diffusion operator

### ISSUE THREAD

**Issue by BrokenDuck** [microsoft/QuantumKatas#459]
Hi, I quickly wanted to say that I did a Q&A style [answer](https://quantumcomputing.stackexchange.com/questions/13313/how-can-you-decompose-grovers-diffusion-operator-into-gates) on quantum stack exchange to better understand the implementation of Grover's diffusion operator with math. Maybe you could add a quick link under the one given in the ReferenceImplementation.qs file. I think it would benefit the understanding of the people learning as the Diffusion operator is probably that hardest to understand thing in Grover's algorithm.

**Comment by tcNickolas** [comment]
That sounds like a good idea. Do you want to send a PR to add that link?

More generally, I've been thinking how to offer a better learning experience for Grover's algorithm - you're right to point out that it's pretty hard to build up intuition for. The current GroversAlgorithm kata is one of the oldest ones we have - it's nearly two years old - and I think we can do much better than that now :-) 

My idea is to create a new tutorial, along the lines of unit 5 of the [MS Learn module on Grover's search](https://docs.microsoft.com/en-us/learn/modules/solve-graph-coloring-problems-grovers-search/) that I just finished writing, but with *a lot more* math (so that the person who wants to dive into the math can do that, and a person who does better gaining intuition can follow the images). It would be the first thing the learner would cover, followed by the current ExploringGroversAlgorithm tutorial that focuses on high-level aspects of the algorithm.
