### ISSUE TITLE
Update notebooks validation script to exclude individual tasks

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#485]
### Context
Currently [validate-notebooks.ps1](https://github.com/microsoft/QuantumKatas/blob/main/scripts/validate-notebooks.ps1) script excludes several notebooks which would fail validation. There are several reasons for failure (see them documented [here](https://github.com/microsoft/QuantumKatas/blob/main/scripts/validate-notebooks.ps1#L84)), and often they affect one or two tasks from the notebook, rather than all of them. Excluding whole notebooks from validation also means that CI can miss issues like invalid JSON in the notebook itself (see an example in #411).

### Improvement
Modify the script so that it's possible to exclude from validation individual tasks, rather than whole notebooks. This would allow us to improve the test coverage by including tasks that can be validated and validating the notebooks formatting. For example, in CHSHGame kata only task 1.2 cannot be validated (since it consists of two cells that would need to be implemented simultaneously, which is not possible with the current implementation), the rest of the tasks can be validated normally.

### Implementation
* The tasks are validated by using `%check_kata` magic in each cell that uses `%kata`, so we shouldn't leave either of these magics in the cell before its validation. 
* We could either remove the magic line altogether for the specified tasks (so that the remaining cell would only define an operation, not run the test on it - which can be an issue if the code skeleton in the cell is invalid), or remove the whole cell for those tasks. This requires some experimentation.
* The syntax of defining the tasks in the script could be something like `'CHSHGame.ipynb#T12_ClassicalStrategy_Test'` instead of the current `'CHSHGame.ipynb'`.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas. Is it necessary to specify the tasks that need to be excluded in the <code>validate_notebooks.ps1</code> script as <code>CHSHGame.ipynb#T12_ClassicalStrategy_Test</code>? <br>

I have a slightly different strategy to solve the problem. 
- Firstly add a tag to the <code>exclude_from_validation</code> to the operations <code>AliceClassical</code> and <code>BobClassical</code> in <code>CHSHGame.ipynb</code> as shown below : 
![excludeFromValidation](https://user-images.githubusercontent.com/40084144/96266529-5e100380-0fe4-11eb-9f96-b671476dae0b.png)

- Then, update the <code>validate_notebooks.ps1</code> script as follows :<br>
<pre>
<code>
if ($env:SYSTEM_DEBUG -eq "true") {
            # Redirect stderr output to stdout to prevent an exception being incorrectly thrown.
            jupyter nbconvert $CheckNotebook --TagRemovePreprocessor.remove_cell_tags="['exclude_from_validation']" --execute --to html --ExecutePreprocessor.timeout=300 --log-level=DEBUG 2>&1 | %{ "$_"}
        } else {
            # Redirect stderr output to stdout to prevent an exception being incorrectly thrown.
            jupyter nbconvert $CheckNotebook --TagRemovePreprocessor.remove_cell_tags="['exclude_from_validation']" --execute --to html --ExecutePreprocessor.timeout=300 2>&1 | %{ "$_"}
        }
</code>
</pre>

<br>

It would be great to know your opinion on the above strategy...

**Comment by tcNickolas** [comment]
This looks like a really neat approach! (I didn't dig deep enough into the Notebooks to find this feature.) I like that the meta-information that defines whether the cell needs to be checked is stored next to that cell itself, rather than in a separate script. 

We'll need to document that carefully - probably somewhere in the contribution guide, and add a link pointing there from `validate_notebooks.ps1`, otherwise it will be hard to discover.

Thank you for the idea!! Will you be working on it?

**Comment by Manvi-Agrawal** [comment]
I would like to work on this issue.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas , I would like to discuss a few things before sending the PR:<br>

Based on some experimentation on my local machine, here is a high level summary of a few things:
- Some of the notebooks which can be removed from <code>not_ready</code> list without excluding any tasks in the notebook. Validation of these notebooks is successful on my local machine :
  - **ComplexArithmetic** and **LinearAlgebra** -- Validation doesnt check if the solutions are correct, it only checks the structure of code. Not sure if it makes sense to remove these notebooks from <code>not_ready</code> list  in the since actual solutions are validated when validation is run against the workbook.
  - **VisualizingGroversAlgorithm** -- validation is successful currently on my local machine, but I am not sure if it would time out in CI often
  - **SolveSATWithGrover** -- validation is successful currently on my local machine, but I am not sure if T32_UniversalGroversAlgorithm() would time out in CI often
  - **Workbook_SolveSATWithGrover.ipynb** -- Similar situation as with SolveSATWithGrover after https://github.com/microsoft/QuantumKatas/pull/538 gets merged. Otherwise, the following operations Oracle_Exactly1OneSATClause, Oracle_Exactly1_3SAT and Run_GroversSearch_Algorithm would need to be excluded.

- Some of the notebooks/workbooks in which some specific tasks need to be excluded
  - **CHSH :** T12_ClassicalStrategy requires implementing two code cells at once before running the test
  - **Workbook_CHSHGame.ipynb :** Either %kata magic needs to be removed OR T12_ClassicalStrategy needs to be excluded. Also, T25_PlayQuantumCHSH needs to excluded if https://github.com/microsoft/QuantumKatas/pull/538 is not merged
  - **MagicSquare :** T11_ValidMove, T13_ClassicalStrategy requires implementing two code cells at once before running the test
  - **GraphColoring and Workbook_GraphColoring.ipynb :** Exclude T23_GroversAlgorithm due to possible timeout in CI as per discussion in https://github.com/microsoft/QuantumKatas/pull/529
  - **ExploringGroversAlgorithm** -- Validation would be successful if we exclude
    - Exercise 3(RunGroversAlgorithm_OutputVerification)
    - Exercise 4 (RunGroversAlgorithm_RerunIncorrectAnswer)
    - Exercise 5(RunGroversAlgorithm_CalculateSuccessProbability)

**Comment by tcNickolas** [comment]
Let's see...
* **SolveSATWithGrover** and **GraphColoring** (and corresponding workbooks) indeed would have their last tasks time out often - since they are randomized, even the reasonable solution will sometimes give incorrect answer on the first few attempts, and if we have 4 notebooks like this in each CI run and run CI several times per day, the probability of one of them timing out is quite high.
* **CHSH**: agree on task 1.2, for 2.5 we should be able to keep it in validation if we increase [the tolerance](https://github.com/microsoft/QuantumKatas/blob/main/CHSHGame/Tests.qs#L162) from 0.01 to 0.1.
* **Workbook_CHSHGame**: I think we have to keep `%kata` in the notebook, since without it one of the solutions is not picked up when the other is executed. Let's exclude task 1.2 here as well.
* **VisualizingGroversAlgorithm**: if I recall correctly, I excluded it because it timed out in CI. We can try not excluding it to check this.
* I don't think it makes sense to run validation on Python tutorials **ComplexArithmetic** and **LinearAlgebra**, since it doesn't check anything about the code, so it just slows the CI down. Ideally we'd figure out a way to validate them as well, similar to `%check_kata` magic, but that's outside of scope of this issue :-)
* **MagicSquare**, **ExploringGroversAlgorithm**: agree
* Also, we see a lot of CI failures for **RandomNumberGeneration** tutorial (makes sense - if we run the tests a lot of time, sometimes randomly generated numbers will look insufficiently random), so we probably want to exclude all tasks in it from validation.
