### ISSUE TITLE
Errors :  Syntax does not match any known patterns & Tasks not recognised errors 

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/QuantumKatas#512]
It seems there is some issue in Jupyter Notebooks due to some recent update to this repository. I am getting the following errors :
- C:\snippet_.qs(1,1): error QS3001: Syntax does not match any known patterns.
- Tests not recognised

It seems the error is because the following lines have been removed from many Jupyter notebooks :
<code>
%package Microsoft.Quantum.Katas::0.12.20082513
</code>
<code>
%workspace reload
</code>

And the simple fix that works is adding those required lines back...

**Comment by rmshaffer** [comment]
Hi @Manvi-Agrawal - can you make sure you please make sure you are running the latest version of IQ#? Here are the update instructions:
https://docs.microsoft.com/quantum/quickstarts/update?tabs=tabid-conda#update-the-iq-jupyter-kernel

If you run `%version`, it should report the following:
![image](https://user-images.githubusercontent.com/3620100/95240436-3f7a6300-07c1-11eb-8a3e-36bd5bbaa136.png)

**Comment by tcNickolas** [comment]
@vivanwin That's the updated scenario for the troubleshooting guide from #476 - the errors are the same but the root cause (and the fix) is slightly different.

**Comment by Manvi-Agrawal** [comment]
Updating iqsharp works @rmshaffer . Although I found a new interesting bug:

Output of <code>conda -f "iqsharp"</code>
Name                    Version                   Build  Channel
iqsharp                   0.12.2010.504            py37_0    quantum-engineering

whereas when I run 
<code>%version in jupyter notebook</code>
Component	Version
iqsharp	0.12.20082513
Jupyter Core	1.4.0.0
.NET Runtime	.NETCoreApp,Version=v3.1

**Comment by rmshaffer** [comment]
Hi @Manvi-Agrawal, thanks for confirming! The mismatched version you are reporting could happen in some cases if you had previously installed a version of IQ# via `dotnet tool install -g Microsoft.Quantum.IQSharp` followed by `dotnet iqsharp install --user`.

To check this, you can run `jupyter kernelspec list`. It should show a path to the installed `iqsharp` kernelspec. If you are inside the `conda` environment where you installed `iqsharp`, then this path should be somewhere inside your `conda` environment path, e.g.:
```
(qsharp-env) PS C:\Users\Ryan> jupyter kernelspec list
Available kernels:
  iqsharp    C:\Users\Ryan\Anaconda3\envs\qsharp-env\share\jupyter\kernels\iqsharp
  python3    C:\Users\Ryan\Anaconda3\envs\qsharp-env\share\jupyter\kernels\python3
```

If your `iqsharp` kernelspec is _not_ under the `conda` environment path, then you may have a per-user installation that is overriding it. In that case, you may see something like:
```
(qsharp-env) PS C:\Users\Ryan> jupyter kernelspec list
Available kernels:
  iqsharp    C:\Users\Ryan\AppData\Roaming\jupyter\kernels\iqsharp
  python3    C:\Users\Ryan\Anaconda3\envs\qsharp-env\share\jupyter\kernels\python3
```

The easiest way to fix this issue is to run `jupyter kernelspec uninstall iqsharp`, which will remove the `dotnet`-installed kernelspec and restore the `conda`-installed kernelspec as the default:
```
(qsharp-env) PS C:\Users\Ryan> jupyter kernelspec uninstall iqsharp
Kernel specs to remove:
  iqsharp               C:\Users\Ryan\AppData\Roaming\jupyter\kernels\iqsharp
Remove 1 kernel specs [y/N]: y
[RemoveKernelSpec] Removed C:\Users\Ryan\AppData\Roaming\jupyter\kernels\iqsharp
```

Then `jupyter kernelspec list` should show the correct, `conda`-installed path:
```
(qsharp-env) PS C:\Users\Ryan> jupyter kernelspec list
Available kernels:
  iqsharp    C:\Users\Ryan\Anaconda3\envs\qsharp-env\share\jupyter\kernels\iqsharp
  python3    C:\Users\Ryan\Anaconda3\envs\qsharp-env\share\jupyter\kernels\python3
```

**Comment by Manvi-Agrawal** [comment]
Thanks @rmshaffer. Now, I am getting the matching version numbers.
