### ISSUE TITLE
[RandomNumberGeneration] Refactor tests

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#557]
In #549 we introduced a new task (generating random numbers from an interval) that uses testing logic very similar to task 3 (generating random numbers with a certain number of bits). It makes sense to refactor the tests as follows:

* Unify `CheckFlatDistributionRange` and `CheckFlatDistribution` to become `CheckUniformDistribution` that would take as input an operation (with no parameters) that generates a random number, and the range from which the number should be picked, and performs the testing.
* We should be able to use [Delay operation](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.canon.delay) to convert each of the operations defined in tasks 1-3 and 5 to a parameter-less operation.
* It should also be possible to calculate the currently passed parameters `lowRange` and `highRange` (and probably `minimumCopiesGenerated`) based on `min`, `max` and `nRuns`, so that `CheckUniformDistribution` would have fewer parameters to configure.
* Finally, we can retry each of the calls to `CheckUniformDistribution` if it failed on the first try - since the numbers generated are random, even a correct solution fails quite frequently. Retrying would make the tests more reliable and enable including this tutorial in the CI build - currently it's [the only notebook excluded from validation altogether](https://github.com/microsoft/QuantumKatas/blob/main/scripts/validate-notebooks.ps1#L128).

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas. Wanted to know your opinions on a few things
- for `lowRange` and `highRange` : I think it should be enough to set them within 3 units of standard deviation(99.9% accuracy)
- For `minimumCopiesGenerated`, I am thinking to use 
` minimumCopiesGenerated = 0.8*numberOfIdealCopies > 40 ? 0.8*numberOfIdealCopies | 0`  ,where
 `numberOfIdealCopies : nruns/(max-min+1)`
- how to use Delay operation? I read from the Documentation provided in the above comment; but I am unable to understand how can Delay operation be used to convert the tasks to a parameterless operation

**Comment by tcNickolas** [comment]
For the first two questions, looks reasonable :-)

For the `Delay` operation, I haven't tried it in code yet, but I believe it would work as follows. 
* Currently `CheckFlatDistribution` takes as an argument a random number generator with signature `(Int => Int)`, with one `Int` parameter and an `Int` return; this means that for the first tasks in which the random number generator is parameterless we need a wrapper like `RandomBit_Wrapper` that takes an extra parameter and just throws it away.
* We can instead change `CheckFlatDistribution` to take a random number generator with signature `(() => Int)` (or `(Unit => Int)`, some experimentation required), and for task 3 pass to it `Delay(RandomNBits, 1, _)` - that is a parameterless operation that, when called, returns `RandomNBits(1)`, but calls it anew each time, so different random numbers will be generated.

**Comment by Manvi-Agrawal** [comment]
- Geeting the following error when I tried to use delay operation:
QS6201	The shape of the given tuple does not match the expected type. Got an argument of type (((Int, Int) => Int), Int, Int, _), expecting one of type (('T => 'U), 'T, Unit) instead.		~\QuantumKatas\tutorials\RandomNumberGeneration\Tests.qs	163	

	My changes:
	- Syntax : `CheckFlatDistributionRange(Delay(RandomNumberInRange,1,3,_), 1, 3, 1.8, 2.2, 1000, 200);`
	- Use : `operation CheckFlatDistributionRange (f : (Unit => Int), min : Int, max : Int, lowRange : Double, highRange : Double, nRuns : Int, minimumCopiesGenerated : Int) : Unit { ... }`

- However, these changes work fine and allow to do away with the wrappers of Random One & Two Bit generation:
	- Syntax : `operation CheckFlatDistribution (f : (Unit => Int), numBits : Int, lowRange : Double, highRange : Double, nRuns : Int, minimumCopiesGenerated : Int) : Unit{..}`
	- Use :  `CheckFlatDistribution(Delay(RandomNBits,1,_), 1, 0.4, 0.6, 1000, 450);`

- **Alternate approach** for unification of CheckFlatDistribution and CheckFlatDistributionRange to CheckUniformDistribution:
  Instead of using Delay operation to convert operation into a parameterless operation, pass the result of the operation to checkFlatDistributionRange.
	- Syntax : `operation CheckUniformDistribution (val : Int, numBits : Int, lowRange : Double, highRange : Double, nRuns : Int, minimumCopiesGenerated : Int) : Unit{..}`
	- Use :  `CheckFlatDistribution(Delay(RandomNBits,1,_), 1, 0.4, 0.6, 1000, 450);`

Wanted to know your opinion if I can go ahead with my alternative approach, or do you want me to use Delay Operation?

**Comment by Manvi-Agrawal** [comment]
And as for reduction in parameters, I think I miscalculated earlier for lowRange and highRange. Seeting lowRange and highRange variables within three unit of standard deviation is  allowing mean to go out out of (min,max) range for some cases :-( 

I talked with @pandasamanvaya who told me that that currently the values for `lowRange` and `highRange` are based on experimentation by running the tests 20-30 times and observing the mean/median. 

By looking at the data, I came with a heuristic to set `lowRange` and `highRange` as `mean +- 0.05*(max-min+1)` and values are very close to the experimentation values. Here is a quick table for reference:

| min | max | new Range[mean +- 0.05*(max-min+1)] | old Range |
| --- | --- | --------------------------------------------- | -------------|
| 0 | 1 | (0.4, 0.6) | (0.4, 0.6) |
| 0 | 3 | (1.3, 1.7) | (1.4, 1.6) |
| 0 | 7 |  (3.1, 3.9) | (3.3, 3.7) |
| 0 | 1023 | (460.3, 562.5) | (461.0, 563.0) |
| 1 | 3 | (1.85, 2.15) | (1.8, 2.2) |
| 27 | 312 | (155.2, 183.8) | (160.0, 180.0) |

Would like to know your opinion on the same

**Comment by Manvi-Agrawal** [comment]
And as for retrying calls to CheckUniformDistribution, I require some time for experimentation since the operation returns a Unit, so how do I assure if a test passed? I am a beginner wrt to Unit Testing.

**Comment by pandasamanvaya** [comment]
Hi @Manvi-Agrawal. After carefully observing the CheckUniformDistribution function, here are some of the insights I would like to share. The distribution generated by the random number generator must be uniform. So, mean = median. This makes median checking redundant if we are checking frequency of each number over nRuns(minimumCopiesGenerated). 
If we consider mean as a random variable then its distribution should be normal because of the central limit theorem. Mean of the normal distribution would be the same = (max+min)/2. But the variance would become (variance of uniform distribution)/nRuns. Variance of uniform distribution = a*(a+1)/3 where a = (max-min)/2(Skipping the derivation). Considering nRuns = 1000, the variance of normal distribution = a*(a+1)/3000. From this we get the lowRange and highRange values as :-

|min|max|mean +- 3*std|mean +- 5*std
|-----|------|----------------|---------------------|
|0|1|(0.45256583509747433, 0.5474341649025257)|(0.4209430584957905, 0.5790569415042095)|
|0|3|(1.3939339828220179, 1.6060660171779821)|(1.323223304703363, 1.676776695296637)|
|0|7|(3.2826293488071583, 3.7173706511928417)|(3.137715581345264, 3.862284418654736)|
|0|1023|(483.45661842787143, 539.5433815721285)|(464.76103071311906, 558.238969286881)|
|1|3|(1.9225403330758517, 2.0774596669241485)|(1.8709005551264195, 2.1290994448735807)
|27|312|(161.6676153056684, 177.3323846943316)|(156.44602550944734 182.55397449055266)|

Hope this helps.

**Comment by Manvi-Agrawal** [comment]
Thanks @pandasamanvaya. This helps a lot. Actually, when I calculated this time, I forgot to divide variance by nRuns, which led to variance going out of range :-( . Do you want to do this task?

**Comment by pandasamanvaya** [comment]
You have already done the hard work. Its better if you continue. I would have to start from the beginning.

**Comment by Manvi-Agrawal** [comment]
Ok @pandasamanvaya.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas, how many times do we want to retry a function? I was thinking of 5 times.

**Comment by tcNickolas** [comment]
* For the number of retries, I imagine that correct solutions will only need the second retry most of the time, and the third one would bring the failure probability negligibly low, so 3 should be enough. Going higher will make testing incorrect solutions (the ones that fail every time reliably) slower, so I wouldn't go too high.
* With the retries in place, I don't think we need to be super precise with the low and high ranges - if the mean or the median go a bit outside of the range in the first run, chances are that the retry will bring them back in the range.
* For `Delay`, I haven't tried it out so my syntax guess might be off - the version that you can come up with that allows us not to introduce a wrapper for each task will be good :-)
