### ISSUE TITLE
Graph coloring bounds

### ISSUE THREAD

**Issue by BrokenDuck** [microsoft/QuantumKatas#563]
Hi, I wanted to ask why we only search for solutions to graphs with maximum 4 colors. Doesn't this take out a big amount of graphs that we cannot color ? I know the four-color theorem states that planar graphs can be colored with 4 colors. Is it linked ?

**Comment by tcNickolas** [comment]
This is related not to the nature of the problems we're solving, but rather to the limitations of the simulation we're using. We want our solutions to be small enough to be possible (and fast!) to simulate on an average laptop, and this means we should use under ~30 qubits. To represent a graph, we need (the number of vertices) * (the number of bits per color) qubits to represent the coloring, plus (the number of vertices) qubits to represent coloring conflicts on vertices. With 4 colors, the number of bits per color is 2 so the total number of qubits stays reasonable for carefully selected graphs; with 5+ colors, we'll need 3 or more qubits per vertex, and the number of qubits will skyrocket so that we won't be able to use full state simulator for any interesting graphs.

We could switch the test for task 2.2 to use ToffoliSimulator, so as to speed up simulation at the cost of limiting our set of available gates, but task 2.3 (Grover's search algorithm itself) requires a broader set of gates than what ToffoliSimulator offers, so we'll still have to stick to 4 colors there.

Anyways, since we're not solving a real graph coloring problem here, but rather teaching the way of thinking and the tools for using Grover's search for solving problems, 4 colors are sufficient for our purposes :-)

**Comment by BrokenDuck** [comment]
Ok, thanks a lot for the answer !
