### ISSUE TITLE
`%kata` magic should use the simulator specified in `@Test` attribute

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#580]
Currently executing a cell with `%kata` or `%check_kata` selects the simulator to use in [this code](https://github.com/microsoft/QuantumKatas/blob/5eb28be678c3bb1cd819a212545ca51657c60481/utilities/Microsoft.Quantum.Katas/KataMagic.cs#L206) - which always uses `CounterSimulator`. This works for now, since all tests are configured to use either `CounterSimulator` or `QuantumSimulator` from which the former is derived, but this will break if we ever define tests that use other simulators.

We should replace this code (and the [matching code](https://github.com/microsoft/QuantumKatas/blob/5eb28be678c3bb1cd819a212545ca51657c60481/utilities/Microsoft.Quantum.Katas/CheckKataMagic.cs#L200) in `%check_kata` magic implementation) with logic that would find the `@Test` attribute, read the simulator configuration from it and use that simulator.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas, a couple of questions to understand the scope of this issue :
- Can [custom simulators](https://devblogs.microsoft.com/qsharp/build-your-own-q-simulator-part-1-a-simple-reversible-simulator/) be used by using `@Test` attribute? Is it in scope of this PR?
- For [`ToffoliSimulator`](https://docs.microsoft.com/en-us/azure/quantum/user-guide/machines/toffoli-simulator):
Currently, it supports [StackTraceDisplay](https://github.com/microsoft/iqsharp/blob/main/src/Jupyter/Extensions.cs#L154) functionality. But I am not sure if the tests using  `ToffoliSimulator` would need to display diagnostic information using `DumpMachine` and `DumpRegister` callable
- For [`ResourcesEstimator`](https://docs.microsoft.com/en-us/azure/quantum/user-guide/machines/resources-estimator) and [`QCTraceSimulator`](https://docs.microsoft.com/en-us/azure/quantum/user-guide/machines/qc-trace-simulator/) : 
They currently support [StackTraceDisplay](https://github.com/microsoft/iqsharp/blob/main/src/Jupyter/Extensions.cs#L154) functionality. I think it might be fine for this scenario since these simulators provide analysis of the resources needed to run a quantum algorithm. It should make less sense for tests using these simulators to call `DumpMachine` and `DumpRegister` callable.

**Comment by tcNickolas** [comment]
* Yes, custom simulators can be used with the `@Test` attribute; you can see an example of a test using `CounterSimulator` [here](https://github.com/microsoft/QuantumKatas/blob/fb048f3d6e46f48788d54cdc93087967ab12049f/PhaseEstimation/Tests.qs#L102), and there is an (unfortunately, internal) example of the `@Test` attribute used with a simulator that is defined in the same project as the Q# code. I guess you could reproduce this last scenario by copying `CounterSimulator` source code to the project, renaming it and using that in tests.
* For non-full-state simulators, their tests will only use the functionality they provide, so if a simulator doesn't provide some functionality, the tests won't use them. If they support `StackTraceDisplay`, there probably will be a scenario in which either the tests will try to be helpful and use `DumpMachine`, or the learner themselves will try to use it in their code to debug the solution.

P.S. Apologies for not reviewing your other PR yet! I'm heads down on prep for https://www.qchack.io/ starting next week :-(

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas, no issues for delayed review. I understand that it requires a lot of efforts goes into planning what tutorials and challenges would go into QCHack event. Looking forward to the event. Meanwhile, I think I would need to revisit a few things in the code to do this task after this clarification.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas, got a few things working on my local machine. Just a few questions.
- Do you need design first or a direct PR would be good?
- Currently, I am able to create all simulators of the type `SimulatorBase` which are either derived from it directly(like `QuantumSimulator`); or indirectly as in the case of `CounterSimulator`(derived from `QuantumSimulator`) and `ReversibleSimulator`(derived from `QuantumProcessorDispatcher` as explained in [this post](https://devblogs.microsoft.com/qsharp/build-your-own-q-simulator-part-1-a-simple-reversible-simulator/) ).
- Also, I am able to simulate a test on multiple simulators which is specified in Q# code as follows 
<pre>
@Test("QuantumSimulator")
@Test("ToffoliSimulator")
@Test("ResourcesEstimator")
 operation QsharpUnitTest() : Unit {
        Message("Worked!");
  }
</pre>

**Additional queries**
- Do we need to support simulators with arguments, and if so how would those simulators be mentioned in `@Test` attribute ?
 Currently `@Test` attribute only invokes the paramterless constructors of the simulators by either specifying the simulator name or by using the fully qualified name as evident in the following examples :
	- `@Test("QuantumSimulator")`
	- `@Test("Microsoft.Quantum.Katas.CounterSimulator")`

- Do we need to support simulator that is defined in the same project as the Q# code?
 That would be a bit difficult since IQ# compiles only the Q# files and not the C# files. As a workaround, we could try to invoke `dotnet build` but then it has its own hassles as explained in https://github.com/microsoft/iqsharp/issues/277#issue-680415148

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas , kindly find the [design document](https://docs.google.com/document/d/1APDB3G9mmfx7aJEe8zd7gm9XUv9JK4nCEzB7O3wbBwI/edit?usp=sharing) for this issue.

I agree this is a bit lengthy, but last 3 pages aren't that important, so you might want to skip them :-) They contain some nitty-gritty details about the code and some other things.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas.
- I was thinking about raising a prototype PR for this issue. This would contain  
    -  Example notebook that has tests running on different simulators
    -  Custom NuGet package that I built on my local machine. 
- Or would you prefer reviewing the [design document](https://docs.google.com/document/d/1APDB3G9mmfx7aJEe8zd7gm9XUv9JK4nCEzB7O3wbBwI/edit?usp=sharing) first?

**Comment by anjbur** [comment]
Hi @Manvi-Agrawal! Your design document looks good to me. For 3a, determining the simulators specified, [this](https://github.com/microsoft/iqsharp/blob/252088342ff3dd6bc7be374ded2b0c0e750a003d/src/Kernel/Extensions.cs#L101) iqsharp code should be useful reference. In that line we're retrieving details about documentation, but it should be similar logic to retrieve the specified simulator so that it can be instantiated through reflection.

**Comment by Manvi-Agrawal** [comment]
Thank you @anjbur for providing the reference to the iqsharp code.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas @anjbur , makes sense to not change `Dockerfile` and the `validate-notebooks.ps1` script since they might cause the build failures.
I would like to know if we want to retain the `Prototype` notebook or not as mentioned in https://github.com/microsoft/QuantumKatas/pull/621

**Comment by Manvi-Agrawal** [comment]
> I would recommend to do a lot of careful manual validation for #620, then merge it with the understanding that the effects will not be observable until the next QDK release in the end of month, and then (after more manual validation that is part of the release process) switch to this change with the next release.

Hi @tcNickolas. How much manual testing are you expecting for #620?
I have tested the effects of changes of `CheckKataMagic` for all notebooks using `%check_kata` locally. So, do you want exhaustive testing for `KataMagic` too? I think that might not be very necessary since `KataMagic` uses logic almost similar to the `CheckKataMagic`. The only difference was the rich jupyter state display for the `QuantumSimulator` and `CounterSimulator` plus the logging messges for all simulators. For that difference, Prototype kata serves as a good aid. Apart from that I ran these tasks locally
- StateFlip of BasicGates kata : uses `DumpMachine` and is simulated on `QuantumSimulator`
- MainDiagonal of UnitaryPatterns kata : simulated on `CounterSimulator`

**Comment by tcNickolas** [comment]
We will be migrating the Katas to the new QDK that will use a different infrastructure (see https://devblogs.microsoft.com/qsharp/introducing-the-azure-quantum-development-kit-preview/ for the announcement), including a much faster simulator, so we won't continue to improve the existing infrastructure of Q# notebooks magics. Closing this issue as "won't fix".

**Comment by Manvi-Agrawal** [comment]
Thanks @tcNickolas and @anjbur for your valuable guidance. 

Looking forward to the new kata experience. Just had a look at https://quantum.microsoft.com/en-us/experience/quantum-katas, and the experience looks way more polished :-)
