### ISSUE TITLE
Possibly switch back to Counter Simulator in Random Number Generation Tutorial

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/QuantumKatas#600]
I am not able to see additional output when tests in `RandomGenerationTutorial` fail. I am testing this in `Visual Studio 2019`. 

I think that is because `ResetOracleCallsCount()` function is defined in `CounterSimulator` and is used by `CheckFlatDistribution()`, `CheckFlatDistributionRange()` and `CheckXPercentZero()`
Because tests pass majority of the time after switching to `CounterSimulator` from `QuantumSimulator` because sometimes numbers aren't very random :D . Please refer to #557. 
On digging utilities/Common/CounterSimulator.cs I found this line :
`public class ResetOracleCallsImpl : ResetOracleCallsCount` at [Line 84](https://github.com/microsoft/QuantumKatas/blob/main/utilities/Common/CounterSimulator.cs#L84)
and in utilities/Common/Utils.qs
`operation ResetOracleCallsCount () : Unit { body intrinsic; }` at [line 21](https://github.com/microsoft/QuantumKatas/blob/main/utilities/Common/Utils.qs#L21)

**Comment by tcNickolas** [comment]
The file `Tests.qs` should definitely use `@Test("Microsoft.Quantum.Katas.CounterSimulator")` instead of `@Test("QuantumSimulator")` - otherwise the tests will fail when running from VS or VS Code because of undefined operation, as you correctly pointed out. Nice catch!

However, when this tutorial is executed as a Jupyter Notebook (which is the main use case scenario, as it is a tutorial, not a kata), the `%kata` magic runs all tests on `CounterSimulator` (see #580). (This is also why the tests can pass that way regardless of incorrect setting in the VS project.) so the switch from `QuantumSimulator` to `CounterSimulator` should have no impact on randomness of tests executed via Jupyter Notebook...

**Comment by Manvi-Agrawal** [comment]
I was thinking of doing this in PR related to #557 since it's a small change. Or do you want me to raise a separate PR for easy review?

**Comment by tcNickolas** [comment]
Yes, combining these two changes in one PR will be fine.
