### ISSUE TITLE
JointMeasurements: Possibly Incorrect task 2 description

### ISSUE THREAD

**Issue by moudrick** [Microsoft/QuantumKatas#67]
There is literally the same description for Task 1 and Task 2 in the topic of Joint measurements.
At the same time, the solutions in ```ReferenceImplementation.qs``` are different and they are not interchangeable for these tasks.

I guess, the incorrect description is for `ParityMeasurement`, Task 2.

Branch: master
File: \\JointMeasurements\Tasks.qs
Line: 43.
See: https://github.com/Microsoft/QuantumKatas/blob/master/JointMeasurements/Tasks.qs#L43

```
    // Task 2. Parity measurement
    // Input: Two qubits (stored in an array) which are guaranteed to be
    //        either in superposition of states |00⟩ and |11⟩
    //        or in superposition of states |01⟩ and |10⟩.
    // Output: 0 if qubits were in the first superposition,
    //         1 if they were in the second superposition.
    // The state of the qubits at the end of the operation should be the same as the starting state.
    operation ParityMeasurement (qs : Qubit[]) : Int {
        // ...
        return -1;
    }
```

Expected:
```
    // Output: 0 if qubits were in the same superposition,
    //         1 if they were in different superposition states.
```

Actual:
```
    // Output: 0 if qubits were in the first superposition,
    //         1 if they were in the second superposition.
```

If this is correct suggestion, I can create a PR for fixing it from my fork or whatever other way.

**Comment by tcNickolas** [comment]
The difference in the descriptions is in the last line (after the output): in task 1 "The state of the qubits at the end of the operation does not matter.", while in task 2 "The state of the qubits at the end of the operation should be the same as the starting state." The solution for task 2 is accepted in task 1, since it performs the same task in a more restricted way.

This pair of tasks shows that you can distinguish the states with different parity using regular measurements, but this will collapse the superposition; to keep superposition you need to use joint measurements which allow to get some information without collapsing the state.

**Comment by moudrick** [comment]
Thanks, @tcNickolas, for explanation. Now I clearly see the difference and its didactic value. So I am closing the issue.

But there is still a question, can there be any practical value in using the solution like in reference for SingleQubitMeasurement instead of that for ParityMeasurement. For example, I know that some quantum operations can consume significantly more energy than others. So are the solutions of these tasks consume energy at the same level or one of them is preferable in terms of energy consuming provided that we don't care the state at the end of operation? 

If this discussion is not relevant here, can you please suggest where can ask this question or start this discussion in context of these Katas?

**Comment by moudrick** [comment]
Also, some noticeable comment regarding this difference in requirements could be introduced somewhere in task description. 
It would be helpful especially for those who go through the katas in parallel with other activities and this is why can easily overlook this important condition.

**Comment by tcNickolas** [comment]
Usually joint measurements use cases are driven not by their efficiency when compared to single-qubit measurements for the same task, but rather by the need to perform a different task (extract some information about the system without collapsing it all the way to a basis state or perform a certain transformation).

A good place for such questions is [Quantum Computing SE](http://quantumcomputing.stackexchange.com/).

This difference is already in task description - right between output and operation signature. It's hard to make it more prominent, since there is only so much formatting we can do in source code :-)
