### ISSUE TITLE
Q# compiler reports that `using y` grammar is being deprecated

### ISSUE THREAD

**Issue by meltyness** [microsoft/QuantumKatas#776]
In the Grover's Search tutorial the following solution may not work permanently -- there may be other instances of this class of issue replicated elsewhere. 

It's worth noting too that syntax has been shuffled around on this twice addressing both :
- modifying the keyword: `using` -> `use` 
- elimination of the parenthesis surrounding the assignment operator `(eval = Qubit())` -> `eval = Qubit()`

https://github.com/microsoft/QuantumKatas/blob/14071e2a044879402bacd8d3a39f7a26ae686603/tutorials/ExploringGroversAlgorithm/ExploringGroversAlgorithmTutorial.ipynb?short_path=c4fa011#L344

**Comment by tcNickolas** [comment]
Indeed the `using` syntax was deprecated about a year ago, and we went through the code updating it to the latest one. But evidently, we missed the old syntax in a couple of places! Looks like there are three occurrences in `ExploringGroversAlgorithmTutorial.ipynb` and one in `Qubit.ipynb`, and they're all in the text of the tutorials rather than in the code cells. That explains how we missed them - we were looking for compiler warnings from running the code in the notebooks!

Thank you for reporting this! Do you want to do the honors and send a pull request to fix those four occurrences of the old syntax? :-) If not, I'll get to it eventually, hopefully some time later this week.

**Comment by meltyness** [comment]
Done! And thank you for building wonderful onboarding into this nascent science!
