### ISSUE TITLE
Sample solutions for task 1.14 of the Superposition katas.

### ISSUE THREAD

**Issue by ivan-shaporov** [microsoft/QuantumKatas#799]
https://github.com/microsoft/QuantumKatas/blob/cd7b60ea618512b0012f16f631c6c780d623841a/Superposition/Workbook_Superposition_Part2.ipynb?short_path=8af21c1#L622

I am looking at the sample solutions for task 1.14 of the Superposition katas. How about another option:
```q#
operation AllStatesWithParitySuperposition (qs : Qubit[], parity : Int) : Unit {
    for i in 1 .. Length(qs) - 1 {
        H(qs[i]);
        CNOT(qs[i], qs[0]);
    }

    if (parity == 1) {
        X(qs[0]);
    }
}
```

It is simpler than what is suggested and passes the tests. Isn't it correct?

**Comment by tcNickolas** [comment]
It looks correct, yes! Passing the tests is a good sign, and I think you can also demonstrate its correctness recursively, since the for loop adds one qubit at a time and keeps the parity of the states even. 

Do you want to add it to the workbook as an alternative solution? It's harder for me to come up with solutions which use gates with a "later" qubit as control and an "earlier" one as target, so this solution can be interesting for learners who have the same "forward-CNOTs" bias :-)

**Comment by ivan-shaporov** [comment]
Thank you @tcNickolas for looking into this. I've created a PR #802
