### ISSUE TITLE
Task 1.15 in Measurements Kata says two states are orthogonal.

### ISSUE THREAD

**Issue by abrassel** [microsoft/QuantumKatas#815]
Task 1.15 seems to make the claim that |S_0> and |S_1> are orthogonal, but it seems as though their inner product is 1.  I sanity checked myself with the following [Wolfram Alpha query](https://www.wolframalpha.com/input?i=inner+product%28%5B1%2C+e%5E%282*pi*i%2F3%29%2C+e%5E%282*pi*i%2F3%29%5E2%5D%2C+%5B1%2C+e%5E%28*pi*i%2F3%29%5E2%2C+e%5E%282*pi*i%2F3%29%5D%29&assumption=%7B%22C%22%2C+%22inner+product%22%7D+-%3E+%7B%22Calculator%22%7D&assumption=%7B%22F%22%2C+%22DotProduct%22%2C+%22dotVector1%22%7D+-%3E%22%5B1%2C+e%5E%282*pi*i%2F3%29%2C+%28e%5E%282*pi*i%2F3%29%29%5E2%5D%22&assumption=%7B%22F%22%2C+%22DotProduct%22%2C+%22dotVector2%22%7D+-%3E%22%5B1%2C+%28e%5E%282*pi*i%2F3%29%29%5E2%2C+e%5E%282*pi*i%2F3%29%5D%22), which seems to confirm my thoughts.

Did I make a mistake somewhere?

**Comment by tcNickolas** [comment]
I believe "inner product" in Wolfram Alpha does not match that used in quantum computing. The one in Wolfram Alpha just performs pairwise multiplication of the input vectors and adds the results, while in quantum computing you multiply one vector by the *adjoint* of the other, taking complex conjugates of the amplitudes of one of the states. The matching Wolfram Alpha query would be [this one](https://www.wolframalpha.com/input?i=inner+product%28%5B1%2C+e%5E%282*pi*i%2F3%29%2C+e%5E%284*pi*i%2F3%29%5D%2C+%5B1%2C+e%5E%28-4*pi*i%2F3%29%2C+e%5E%28-2*pi*i%2F3%29%5D%29), with the amplitudes of the second vector being e^(-4πi/3) and e^(-2πi/3) - then the result is 0 indeed.

Additionally, the solution to this task confirms that the states are orthogonal - otherwise we wouldn't be able to distinguish them perfectly!

**Comment by abrassel** [comment]
That makes sense!
